### ISSUE TITLE
current branch not pushed when `PUSH_ALL_REFS=false`

### ISSUE THREAD

**Issue by skarzi** [spyoungtech/mirror-action#15]
hi :wave: 

first of all thanks for maintaining really cool Github Action!
I wanted to use your action to push just the `main` branch and tags to the mirror repo with the following action:

```yaml
---
name: mirror repository
'on':
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: mirror to bitbucket
        uses: spyoungtech/mirror-action@v0.4.3
        with:
          REMOTE: git@bitbucket.org:my-org/my-repo.git
          GIT_SSH_PRIVATE_KEY: >-
            ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false
```

The problem is that this workflow run pushes only `tags` to bitbucket repo, the current branch (`main`) is not pushed at all like suggested in `PUSH_ALL_REFS` docs in `action.yml`:

> Push all refs instead of just the current branch
