### ISSUE TITLE
Can mirror-action be used for a pull vs push?

### ISSUE THREAD

**Issue by connecteev** [spyoungtech/mirror-action#8]
@spyoungtech first off thanks for this useful project. Is it possible to use this to mirror a repo as a "Pull" rather than a "Push"?

My understanding is as such:
- The mirror-action yml file needs to be added to a *local* repo A (that you own), and the action would "push" all branches from your local repo A to your remote repo B (on github, gitlab, bitbucket, what have you).

Can this action be used to "pull" instead? The situation is as such: I have read-only access to a private github repo, and I would like to mirror all branches from that repo into one I own and control. If it's possible, what would the yml config look like?

So far I was trying to use https://github.com/actions/checkout but I probably didnt end up configuring it right. A search led me to your repo.

**Comment by connecteev** [comment]
Thanks @spyoungtech In my case, both the source and destination (REMOTE) repos are on github.
Source: private github repo that I have read-only access to
Destination: private github repo that I own (and have write access to)

I want to be able to mirror / sync all branches from the source to the destination. An example yml would be helpful.

**Comment by spyoungtech** [comment]
Understood. For this purpose, you'll probably need to use a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) (PAT) with the checkout@v1 action like so

```yaml
- uses: actions/checkout@v1
  with:
    repository: myAccount/my-read-only-repository
    token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret contains your PAT.
```

Then the following step, use this repo's parameters as normal, specifying the present repository as the remote. For example

```yaml
      - uses: spyoungtech/mirror-action@v0.4.0
      with:
        REMOTE: git@github.com/myAccount/my-repo.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_SSH_PUBLIC_KEY: ${{ secrets.GIT_SSH_PUBLIC_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true" # or specify GIT_SSH_KNOWN_HOSTS, recommended
```
